### ISSUE TITLE
NETFLIX

### ISSUE THREAD

**Issue by marioeivissa** [DevLARLEY/WidevineProxy2#1]
excellent extension!!!!congratulations to DevLARLEY im impressed!!!!!works with all providers i tried already, but some issue with netflix, It logs me out of Netflix when I use the extension, anyhelp????thanks for hard job

**Comment by DevLARLEY** [comment]
The thing is, it should theoretically work on Netflix too but I've tested it already and it doesn't work, probably because they either don't accept your type of Android CDM or just the fact that it's an Android CDM. This will require more testing

**Comment by marioeivissa** [comment]
> El problema es que, en teoría, también debería funcionar en Netflix, pero ya lo he probado y no funciona, probablemente porque no aceptan tu tipo de CDM de Android o simplemente porque es un CDM de Android. Esto requerirá más pruebas.

ok ill try more cdm diferents devices, thanks crack

**Comment by marioeivissa** [comment]
What is incomprehensible to me is how you have managed to "decode" certain licenses that contained a very long answer to obtain the keys, I was never able to through the web, I have had to resort to the app, impossible through the web, which with your extension is they take out without problems, like for example Vodafone and even Amazon, which also requires also a pssh on SD to get keys, im super impressed my friend, very good job

**Comment by DevLARLEY** [comment]
There a part of the browser called EME, through which all challenges and responses, etc. must travel (in plain text). All the extension is doing is intercepting the license and challenge at that point. I'm not sure why Amazon is working, because, as you already said they required an SD PSSH.

**Comment by marioeivissa** [comment]
> There a part of the browser called EME, through which all challenges and responses, etc. must travel (in plain text). All the extension is doing is intercepting the license and challenge at that point. I'm not sure why Amazon is working, because, as you already said they required an SD PSSH.

its working perfectly mate for amazon also, believe me, amazing extension very nice job,
