### ISSUE TITLE
Movistar+ Spain MPD better quality

### ISSUE THREAD

**Issue by 1YZTOOAr** [DevLARLEY/WidevineProxy2#10]
Hello, good morning:

Could an improvement be added to the Movistar+ Spain provider to transform the MPD [DASH] from "manifest.mpd" to "manifestgen.mpd"? This change improves the bitrate quality from 5000kbps to 8000kbps for both downloading and playback.

For example:

5000kbps: https://vod-dash-movistarplus.emisiondof6.com/prod/dash/skymd.................../manifest.mpd  

8000kbps: https://vod-dash-movistarplus.emisiondof6.com/prod/dash/skymd.................../manifestgen.mpd

**Comment by DevLARLEY** [comment]
I will not add support for specific services
