### ISSUE TITLE
ITVX  developed cmd fails to parse when run.

### ISSUE THREAD

**Issue by vinefeeder** [DevLARLEY/WidevineProxy2#13]
CMD fails.

N_m3u8DL-RE "https://itvpnpdotcom.blue.content.itv.com/10-5893-0001-001/34/1/VAR028-HD-s/10-5893-0001-001_34_1_VAR028-HD-s.ism/.mpd?filter=%28%28type%3D%3D%22video%22%26%26DisplayHeight%3C%3D720%29%7C%7C%28type%21%3D%22video%22%29%29&hdnea=st%3D1734266504~exp%3D1734288104~acl%3D/10-5893-0001-001/%2A~hmac%3D99f6e204647e2178def813404a197dc2312a8bc2778ad8da92ce9b68a761bc5e" -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0" -H "Accept: */*" -H "Referer: https://www.itv.com/" -H "Origin: https://www.itv.com" -H "DNT: 1" -H "Cookie: _abck=E32F31D91DD168C667223D87351DD18A~-1~YAAQzaMQAtO+zbaTAQAAaIFWyg0xYunLQTLrvsIMoUU5nE9jokRNQfkiwXgf5kL0Kq7nGv+nrVXHT4tXHWw0cExhjW3ANFFw9shEDqWUnkd24FLMZ8HZIz4Bdse/3a6WPGtW48EZXAozLz8x+ROShXt0JpUE1or4R2iY/oth4tkubvgfotb2L1qasXBakAfK+w/9VE0uT7CNVSrgOxWvyhPDAS3zgbqnzWrYyp4i3rU5Q5Y1s1hIP/F/7Hfo9sj91o5Cc0VefcsZmFLSSb3mq3coqKEusgjnGzl0LvQHtH5BmwFT1222ijZd4GZOcr7PTMJ7tAQV6CzS51ZPD9t891cFk1cpJwFOfBojJ+GDs+64BB8dDPO+48GO3jMSuqyHGqfzjuRTmM1W/BnMPWpf4DHZfPgArd+hM5tMDJ76m1UWicQdPECB1PcF1rgqO+vEjJFjz1jUuLJvYshHVHw9pShzd3crJXzw2paN~-1~-1~-1; bm_sz=8CE67E6521217B157BF59CBB5C82042C~YAAQzaMQAtrCzbaTAQAAT+lWyhqvhqgKIijxtYi3s/8fmjdTg9821CTCtj4ny4UfTSk5ookwxkvSdW/IAV7GAhpvpDqlZ5q3L7IoLETW7krBK+9m0ao8a0rqkfDNRd0gR9/daNzFSm7zNsXY3F6h5HexjlUlajtFodkapAkugw02oVKVtdBehLwqOaNl69neYBqrfNMtJuRc2mNxKAIPqW32mP6hOfgsoZyvW/2QKemPNIl26V2BKShm2vB7iQ15FZ1bTuVmKd4Lk/Gx52xb2p58ojh6avbu7BAZYD5kPeuD+dc7Y3gfyhMtiXCQQiOlSMsJEm4prwxUcFVar7UW1eSquDVQ40mjIYHYWlt5gkY3ch1e038YaRObgaqo25qvQsAkSl8bvqzg5I/fuWoVbRycnpa/4Hjb0/+X3ZgKCbYB~3355202~4337732; Itv.Cid=ec0d63f1-6e90-46bf-8785-5dc1edd04973; Itv.Session={'tokens':{'content':{'entitlement':{'purchased':[],'source':'','failed_availability_checks':[]},'email_verified':true,'token_type':'bearer','access_token':'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2F1dGguaXR2LmNvbSIsInN1YiI6IjQ3ZGYzMGY1LWRjNmUtNDRmNi05MDgzLTk0ZGQ0NTI2OTMwOSIsImV4cCI6MTczNDM1NjUxNCwiaWF0IjoxNzM0MjY2NTE0LCJicm9hZGNhc3RFcnJvck1zZyI6IiIsImJyb2FkY2FzdFJlc3BvbnNlQ29kZSI6IjIwMCIsImJyb2FkY2FzdGVyIjoiSVRWIiwiaXNBY3RpdmUiOnRydWUsIm5vbmNlIjoiY2VyYmVydXMtYXV0aC1yZXF1ZXN0LTE3MzQyNjY1MTI3MjUiLCJuYW1lIjoiTW9yZXRvbiIsInNjb3BlIjoiY29udGVudCIsImVudGl0bGVtZW50cyI6W10sInBheW1lbnRTb3VyY2UiOiIiLCJzaG93UHJpdmFjeU5vdGljZSI6ZmFsc2UsInVuZGVyMTgiOmZhbHNlLCJhY2NvdW50UHJvZmlsZUlkSW5Vc2UiOiI0N2RmMzBmNS1kYzZlLTQ0ZjYtOTA4My05NGRkNDUyNjkzMDlfMCIsInJlZ2lvbiI6Im1lcmlkaWFuX2Vhc3QiLCJwb3N0Y29kZVZhbGlkYXRlZE9uIjpudWxsLCJwcm9maWxlVHlwZSI6Ik1haW4ifQ.O9zifG0x5gp8LPQFGm1I6D5Fet5CW7VyJDv_kIP-m3BjbjM7dKe6uQNn1BnQQWZyhPwvi8ANEZK1GXzBDWWxOjoSdDmIlglrM0fbhA95Ty5Exz4imYN-nK216ItekO2toCmDa0gZpbiHbphOexku57r0G1veoMB6QM2FXEk7PZ9GBLiK4lKibYXOHnXPUeVvppnUd85mEHuxLcnMl3L8yeqTHhOjS9FDbBwcVDGgJvV4EmC0dLttt70RZpBwKUg0z9tzIihaV3QRRlD3eTHG0x1-Kaft9s8nfP6XmejVs1o4V6F1IkzW2lHjQ7GGEkGY8y2o-oIXF_jX6jnsH2izpw','refresh_token':'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2F1dGguaXR2LmNvbSIsInN1YiI6IjQ3ZGYzMGY1LWRjNmUtNDRmNi05MDgzLTk0ZGQ0NTI2OTMwOSIsImV4cCI6MTc2NTgwMjUxNCwiaWF0IjoxNzM0MjY2NTE0LCJub25jZSI6ImNlcmJlcnVzLWF1dGgtcmVxdWVzdC0xNzM0MjY2NTEyNzI1Iiwic2NvcGUiOiJjb250ZW50IiwiYXV0aF90aW1lIjoxNzM0MjY2NTE0LCJhY2NvdW50UHJvZmlsZUlkSW5Vc2UiOiI0N2RmMzBmNS1kYzZlLTQ0ZjYtOTA4My05NGRkNDUyNjkzMDlfMCIsInByb2ZpbGVUeXBlIjoiTWFpbiJ9.RWK_cb0G2JI1YHkv98PAR8zjUSl-A4nOxussiKA3mSWXIKYFMK38q_gQdLJRzasFkc1pgBgduvQE9cOltZWFEmHqrYF0XApmX8vzinjcSDstpiq2kDRSzT-9ALjBBchHVxPqsaSipMeqMm-GsFB6GLe3kYgs273pSvZ1p7-TFQnfgNizhgKctjLCLWSVk2ZoVl6n4gfIQDB7Nq_ypigVFJRZ7tRjqRbvCcPcL9GJ_bey7kjGjbrHj86zSs5B-p-4InXRJr3g2ydHPo3iUHQzJkIBDNlxdPqX3jkQT8qsh_7M3HANEp2XVVAZ5CKPl1Wr3Wo-dYvpo7MrHVn7WGU9Jw','profile_token':'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2F1dGguaXR2LmNvbSIsInN1YiI6IjQ3ZGYzMGY1LWRjNmUtNDRmNi05MDgzLTk0ZGQ0NTI2OTMwOSIsImV4cCI6MTczNDI3MDExMywiaWF0IjoxNzM0MjY2NTEzLCJub25jZSI6ImNlcmJlcnVzLWF1dGgtcmVxdWVzdC0xNzM0MjY2NTEyNzI1IiwibmFtZSI6Ik1vcmV0b24iLCJ1bmRlcjE4IjpmYWxzZSwic2NvcGUiOiJwcm9maWxlIiwicmVnaW9uIjoibWVyaWRpYW5fZWFzdCIsInBvc3Rjb2RlVmFsaWRhdGVkT24iOm51bGx9.FL79CXCwJxcUfVbTRNbrJp3cVghcc0Wclurb4GhJiHBNKc6ZC30CdkguA5F0wiuAuyLQRI8onarSVVYb4exj-8M7YUZQPd-k2xZSLTytkU82sIgZw3WQ8YKu9fa2r9KoXfVZmrwYGgQFc6yjcu8U-bG6NXiKezYyyeUPW1U_41PkKIL6krM_t8tzvYbCjMWp-nggdyQymC8JtZ5iWKc-ZzTbqKvgTmJ01ve8vFczYbjsauQyEYNW8BMjUb0E1MkrH211_lbHPW-azkXtilkedyCrfY_83imC_vk1Nfk6PsqkbUGTrZDAAmR8DYodkP5rOZRbRHubHver4JjV0UlW6Q','missingUserData':['noplanselected']}},'sticky':true,'redirect':'/watch/scrubs/10a5893/10a5893a0001'}; mid=888599434615567109; Itv.cck={}" --key 1d488592b00049209679e6e1ddf0cd2b:e8c1cea0b61d0df648cc28c273e1d2ff --use-shaka-packager -M format=mkv

13:03:34.839 INFO : N_m3u8DL-RE (Beta version) 20241201
13:03:34.841 ERROR: Input string was not in a correct format. Failure to parse near offset 1180. Expected an ASCII digit.

**Comment by vinefeeder** [comment]
Strike outs above are attributable to github.

**Comment by DevLARLEY** [comment]
Caused by the `{` and `}`. Removing the cookies helps

**Comment by vinefeeder** [comment]
Thanks, but I got it first time with HellYes
