### ISSUE TITLE
Extension breaks some websites due to "ReferenceError: MediaKeyMessageEvent is not defined"

### ISSUE THREAD

**Issue by fireattack** [DevLARLEY/WidevineProxy2#16]
After installing this extension, I noticed that the "TP-LINK ID" page in my router's admin console became non-functional, even when this WebExt is not "enabled" in the dropdown setting menu.

### Normal:  
![image](https://github.com/user-attachments/assets/cf4e9da3-d96d-4b17-8e8b-b9eb545cee75)  

### Broken:  
![image](https://github.com/user-attachments/assets/ade50522-1975-4bb8-bacb-fb5e846b4824)  

Upon inspecting the console, I found multiple uncaught errors originating from `content_script.js`, such as:  

```
Uncaught (in promise) ReferenceError: MediaKeyMessageEvent is not defined
    at wrappedListener (content_script.js:102:46)
```  

This seems to interfere with the router's admin Web UI's built-in JavaScript code, likely causing the page to break.

**Comment by DevLARLEY** [comment]
Issues like this are pretty much bound to happen and it's not possible to find a cause or even fix it

**Comment by fireattack** [comment]
I'm thinking of a simple fix, e.g. just checking if MediaKeyMessageEvent class is defined first. Is it possible?

**Comment by DevLARLEY** [comment]
Hm, I expected the listener itself to collide with the TP-LINK panel.
I'll do some testing of your fix before accepting it
