### ISSUE TITLE
Vdocipher & inkryptvideos

### ISSUE THREAD

**Issue by adx0-a** [DevLARLEY/WidevineProxy2#2]
Hello brother 
when i was trying to extract keys vdocipher with real cdm
the first response works good but 
in the second auth response it shows that `{"code":2074,"message":"Please open in Android app","isErrorRecoverable":true}`
that is the mpd : https://d3dac6kw5cbsk4.cloudfront.net/media/L95I85q8nZu9y/9e03f0c7/stream.mpd
and that not on all vdocipher videos like the https://www.vdocipher.com/ demo video i can extract keys but not all videos 
and can u please add inkryptvideos key extract its looks like vdocipher 
it uses https://license.inkryptvideos.com/api/v1/wj/license
and at least thanks for ur works

**Comment by DevLARLEY** [comment]
There is nothing I can do if the license server denies the license. The only cause is the CDM, and 'Android app' sounds like they're trying to use L1. You could try to play the video on a device that does not have L1 anymore or where it's been disabled. If that doesn't work too then it's clear that they're trying to use L1.

Is there a video in the browser that is protected by Incrypt or are all of their videos app only?

**Comment by adx0-a** [comment]
1 : about the vdocipher is that mean its cdm problem 

2 : yeah there are videos on browser but idk them which i know is paid 

but its works on browser

**Comment by adx0-a** [comment]
ad i see the extension works in change cdm i mean the video thinks i am android 
because he send `You can only play this video using the verified player:
1- Download & install player from Google Play Store
2- Come back to this page again
3- click on (open player)`

in video player window
but when i disable the extension 
the window send this `Movie Player error 6007-1001-11117 : This Browser is not supported, please use (Chrome) to view this video
`

about license 


first auth 

curl 'https://license.inkryptvideos.com/api/v1/wj/license' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.7' \
  -H 'content-type: application/json' \
  -H 'in-s: 4ce3568817d252e484c2e28a782269a8390a178621b190314dd1e7ab3fc8a139' \
  -H 'ink-ref: https://khaled-sakr.com/course/2/sections/1/video/1972' \
  -H 'origin: https://resource.inkryptvideos.com' \
  -H 'priority: u=1, i' \
  -H 'referer: https://resource.inkryptvideos.com/' \
  -H 'sec-ch-ua: "Chromium";v="130", "Brave";v="130", "Not?A_Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' \
  -H 'x-otp: 4ee7ac2292d74cb9b5258f38c5a9819f57ecab8fb6a24dbdb72c3916ac624ba5' \
  -H 'x-version: 2.1.83' \
  --data-raw '{"token":"eyJ2IjoiYWEzZ......"}'
  
  like vdocipher 
  and the response is 
  
  {
    "l": "CAUSxwUKwQIIA.....",
    "c": "eyJ0eXBlIjoicnRl......"
}
 the second 
 
 curl 'https://license.inkryptvideos.com/api/v1/wj/license' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.7' \
  -H 'content-type: application/json' \
  -H 'in-s: 4ce3568817d252e484c2e28a782269a8390a178621b190314dd1e7ab3fc8a139' \
  -H 'ink-ref: https://khaled-sakr.com/course/2/sections/1/video/1972' \
  -H 'origin: https://resource.inkryptvideos.com' \
  -H 'priority: u=1, i' \
  -H 'referer: https://resource.inkryptvideos.com/' \
  -H 'sec-ch-ua: "Chromium";v="130", "Brave";v="130", "Not?A_Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' \
  -H 'x-otp: 4ee7ac2292d74cb9b5258f38c5a9819f57ecab8fb6a24dbdb72c3916ac624ba5' \
  -H 'x-version: 2.1.83' \
  --data-raw '{"token":"eyJ2IjoiYW........"}'
  
  response :
`  {"success":false,"code":21101,"message":"Please use inkrypt player for android"}`

but i want to say the video player is still working i sitll can un the video

**Comment by adx0-a** [comment]
and another q. 
what if i use the extension on phone using browser for vdocipher is it will works
or will saying Please open in Android app 
and why some vdocipher works but that video not and saying Please open in Android app

**Comment by DevLARLEY** [comment]
The extension is not supported on Android browsers.
They probably have some settings where you can set the level of security for videos.

**Comment by adx0-a** [comment]
what about why some vdocipher video can get keys but that video can't

**Comment by DevLARLEY** [comment]
Read
> They probably have some settings where you can set the level of security for videos.

**Comment by DevLARLEY** [comment]
I don't know that was a wild guess

**Comment by adx0-a** [comment]
ok, at all thanks an if u can please try add inkrypt video

**Comment by DevLARLEY** [comment]
there is nothing I can do if a video is not supported **it's directly caused by your CDM**

**Comment by adx0-a** [comment]
😞
does there way to using dll widevine ?
