### ISSUE TITLE
i used it for vdocipher and these error happened

### ISSUE THREAD

**Issue by dyaaYTzead** [DevLARLEY/WidevineProxy2#3]
{code: 2074, message: "Please open in Android app", isErrorRecoverable: true}
code
: 
2074
isErrorRecoverable
: 
true
message
: 
"Please open in Android app"

**Comment by DevLARLEY** [comment]
Some vdocipher videos work, some don't. It's a problem with your CDM. My guess is that they require L1.

**Comment by dyaaYTzead** [comment]
so is there a way to download it ??

**Comment by qazwsdc** [comment]
> Some vdocipher videos work, some don't. It's a problem with your CDM. My guess is that they require L1.

actually some vdocipher video must need Android app to play and some doesn't(directly play in Android chrome).
the extension only works on second situation

**Comment by dyaaYTzead** [comment]
so this video https://www.vdocipher.com/blog/upload-import-embed-overview-tutorial/ should work ?
