### ISSUE TITLE
Kiwi Browser

### ISSUE THREAD

**Issue by fawyrad** [DevLARLEY/WidevineProxy2#5]
I was unable to import this extension into Kiwi Browser, Android app (based on Chromium and WebKit which support Chrome extension features). But, I can successfully import  Widevine L3 Guesser extension by FoxRefire. Kiwi Browser support load unpacked extension with developer mode same as official Chrome.

**Comment by DevLARLEY** [comment]
There's no error message so I can't really do anything. I can import the extension on Firefox Nightly for Android but can't choose a file, probably because the popup window isn't supported. I'll bookmark this issue and add mobile support in the future

**Comment by fawyrad** [comment]
I managed to successfully import the extension into Kiwi Browser after reading the information from here:
https://developer.chrome.com/docs/extensions/develop/migrate/to-service-workers

```
Update the "background" field in the manifest
In Manifest V3, background pages are replaced by a service worker. The manifest changes are listed below.

Replace "background.scripts" with "background.service_worker" in the manifest.json. Note that the "service_worker" field takes a string, not an array of strings.
Remove "background.persistent" from the manifest.json.
```

So, I remove _"scripts": ["background.js"],_ from manifest.json file and repacked again your extension into .zip and import back to Kiwi Browser. I tried my streaming website with the modified version extension and it can decrypt the keys successfully like I did on my laptop.
