### ISSUE TITLE
Faile to download videos form crunchyroll.

### ISSUE THREAD

**Issue by superlogix** [DevLARLEY/WidevineProxy2#7]
Test url: https://www.crunchyroll.com/watch/G7PU3PWDW/today-i-just-want-to-go-home
WidevineProxy2 can detect key and mpd url.  But N_m3u8DL get an forbidden error when downloading mpd file.

**Comment by DevLARLEY** [comment]
No idea... The manifest is only requestable via N_m3u8DL-RE when the video is playable (aka. the addon is disabled or keys have already been obtained). I'll just leave this open

**Comment by october262** [comment]
are you signed in to crunchyroll ??

**Comment by berny6969** [comment]
> Test url: https://www.crunchyroll.com/watch/G7PU3PWDW/today-i-just-want-to-go-home WidevineProxy2 can detect key and mpd url. But N_m3u8DL get an forbidden error when downloading mpd file.

crunchyroll need some headers on cmd to download my friend

**Comment by berny6969** [comment]
> No idea... The manifest is only requestable via N_m3u8DL-RE when the video is playable (aka. the addon is disabled or keys have already been obtained). I'll just leave this open

Forget about this problem, chrunch needs headers to download, apart from being premium for many videos

**Comment by superlogix** [comment]
The key to the problem is that if the WidevineProxy2 extension is not loaded, the sniffed MPD can be downloaded and decrypted with the key; after loading the WidevineProxy2 extension, the video cannot be played and the sniffed MPD cannot be downloaded. The reason for the failure to download is related to the extension modifying the DRM request data, causing the server verification to fail?
